org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.warning.mode=none

authors=["BillyGalbreath"]
description=LiveMap is a high-performance, minimalistic world map viewer for Minecraft servers. Built as the official evolution of Pl3xMap, it delivers crisp, vanilla-style 2D rendering with a fraction of the resource overhead found in traditional map plugins.
website=https://modrinth.com/plugin/livemap
sources=https://github.com/BillyGalbreath/LiveMap
issues=https://github.com/BillyGalbreath/LiveMap/issues
