org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.warning.mode=none

authors=["BillyGalbreath"]
description=LiveMap is a minimalistic and lightweight world map viewer for Minecraft servers using the vanilla Minecraft rendering style
website=https://modrinth.com/plugin/livemap
sources=https://github.com/BillyGalbreath/LiveMap
issues=https://github.com/BillyGalbreath/LiveMap/issues
