settings:
  debug-mode: false
world-settings:
  default:
    enabled: false
  world:
    enabled: true
    order: 0
    display-name: Overworld
    render:
      renderers:
        - id: fancy
          type: fancy
          name: Fancy
          icon: overworld_fancy.png
          heightmap: fancy
          biome-blend: 2
          translucent-fluids: true
          noise: true
  world_nether:
    order: 1
    display-name: The Nether
  world_the_end:
    order: 2
    display-name: The End
